spring:
  application:
    name: anonymous-map
  datasource:
    url: jdbc:mariadb://localhost:3307/anonymous-map
    username: anonymous-map_user
    password: qwe321!!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%X{requestId:-NO_REQ}] %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace  # 쿼리 파라미터 값 출력
    com.yongman: debug
