spring:
  application:
    name: anonymous-map
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3307/anonymous-map}
    username: ${DB_USERNAME:anonymous-map_user}
    password: ${DB_PASSWORD:}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%X{requestId:-NO_REQ}] %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: ${LOG_LEVEL_SQL:info}
    org.hibernate.orm.jdbc.bind: ${LOG_LEVEL_BIND:off}
    com.yongman: ${LOG_LEVEL_APP:info}
